name: Fly Deploy
on:
  push:
    branches:
      - 'master'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Add dummy dev.secret.exs file to pass compilation
        run: touch config/dev.secret.exs
      - uses: erlef/setup-beam@v1.17
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.0-otp-26
      - name: Cache deps and build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('config/**') }}
          restore-keys: |
            ${{ runner.os }}-mix-   
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
  deploy:
      name: Deploy to fly.io
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
